variables:
  DOCKER_USERNAME: "bizara"


stages:
  - testing
  - build
  - deploy

build-docker-image:
  stage: build
  tags: 
    - group_docker 
  before_script:
    - echo '登入 docker hub'
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  script:
    - echo '打包 docker image'
    - docker build -t $DOCKER_USERNAME/fastapi_pss .
    - docker push $DOCKER_USERNAME/fastapi_pss

deploy-to-production:
  stage: deploy
  tags:
    - group_docker 
  # needs:
  #   - build-docker-image
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - echo '部屬 image 到EC2'
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$EC2_IP "
        ./1140402_fastapi/deploy.sh"
